#!/bin/sh

P2AVER="0.0.4"

FILE="$1"

case "$1" in
	""|"-h"|"--help"|"help")
		printf "\n USAGE:\n"
		printf "	portable2appimage \"FILE\"\n"
		printf "	portable2appimage \"FILE\" \"APP\"\n"
		printf "	portable2appimage \"FILE\" \"APP\" \"VERSION\"\n"
		printf "\n See https://github.com/ivan-hc/portable2appimage for more information.\n\n"
		exit 0
		;;
	"-v"|"--version"|"version")
		printf "%b\n" "$P2AVER" && exit 0
		;;
esac	

APP="$2"
[ -z "$APP" ] && APP="$FILE"

APPDIR="$APP.AppDir"

mkdir -p tmp "$APPDIR" && cp "$FILE" tmp/
cd tmp || exit 1

################################################
# Check if FILE is an archive
################################################

if test -e ./*7z; then 7z x ./*7z 2>/dev/null && rm -f ./*7z; fi
if test ./*.deb; then ar x ./*.deb && rm -f ./*.deb && tar fx ./data.tar* && rm -f ./*tar.*; fi
if test -e ./*tar.*; then tar fx ./*tar.* && rm -f ./*tar.*; fi
if test -e ./*zip; then unzip -qq ./*zip 1>/dev/null && rm -f ./*zip; fi

mv ./* ../"$APPDIR"/ && mv ../"$APPDIR" ./ && cd "$APPDIR" || exit 1

################################################
# Find main executable
################################################

EXEC=$(find . -type f -name "$APP" -executable 2>/dev/null | sed 's/^.//g' | head -1)
[ -z "$EXEC" ] && echo "No executable found, exiting." && exit 0

################################################
# Add version
################################################

if [ -z "$3" ]; then
	VERSION=$(strings "$(find . -type f -name "$APP" -executable 2>/dev/null | head -1)" 2>/dev/null | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)
else
	VERSION="$3"
fi

################################################
# Compile the AppDir
################################################

# Add AppRun
cat > "AppRun" <<EOF
#!/bin/sh
HERE=\$(dirname "\$(readlink -f "\$0")")
exec "\$HERE/$EXEC" "\$@"
EOF
chmod a+x "AppRun"

# Add .desktop file
DESKTOP_FILE=$(find . -maxdepth 10 -type f -name "*.desktop" -exec grep -q "^Exec=.*fdm" {} \; -exec grep -q "^Icon=" {} \; -print | head -1)
if [ -n "$DESKTOP_FILE" ]; then
	cp "$DESKTOP_FILE" ./
fi
if ! test -f ./*.desktop || ! test -f ../../*.desktop; then
	cat <<-HEREDOC >> "$APP.desktop"
	[Desktop Entry]
	Type=Application
	Name=$APP
	Exec=$(echo "$EXEC" | sed 's#^/##g')
	Icon=$APP
	Terminal=false
	Categories=Utility;
	HEREDOC
fi

# Add icon
ICON_ENTRY=$(cat ./*.desktop | grep "^Icon=" | head -1 | sed 's:.*/::' | sed 's/.png//g; s/.svg//g; s/Icon=//g')
sed -i "0,/^Icon=/s|^Icon=.*|Icon=$ICON_ENTRY|" ./*.desktop 2>/dev/null
ICON=$(find . -maxdepth 10 -type f \( -iname "$ICON_ENTRY.png" -o -iname "$ICON_ENTRY.svg" -o -iname "$ICON_ENTRY.xpm" \) 2>/dev/null)
if [ -z "$ICON" ] || [ ! -f ../../"$ICON_ENTRY.png" ] || [ ! -f ../../"$ICON_ENTRY.svg" ] || [ ! -f ../../"$ICON_ENTRY.xpm" ]; then
	printf '\x89PNG\r\n\x1a\n' > "$APP.png"
else
	cp "$ICON" ./
fi

# Finalize
cd .. || exit 1
if ! test -f "$APPDIR"/*.desktop; then
	cp ../*.desktop "$APPDIR"/ 2>/dev/null
fi
if [ ! -f "$APPDIR"/"$ICON.png" ] || [ ! -f "$APPDIR"/"$ICON.svg" ] || [ ! -f "$APPDIR"/"$ICON.xpm" ]; then
	cp ../"$ICON".png "$APPDIR"/ 2>/dev/null || cp ../"$ICON".svg "$APPDIR"/ 2>/dev/null || cp ../"$ICON".xpm "$APPDIR"/ 2>/dev/null
fi

################################################
# Export to AppImage
################################################

_appimagetool() {
	if ! command -v appimagetool >/dev/null; then
		[ ! -f ./appimagetool ] && \
		curl -#Lo appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-"$ARCH".AppImage && \
		chmod a+x ./appimagetool
		./appimagetool "$@"
	else
		appimagetool "$@"
	fi
}

ARCH=x86_64 VERSION="$VERSION" _appimagetool -s "$APPDIR" 2>&1

if ! ls ./*.AppImage >/dev/null 2>&1; then
	echo "No AppImage available."
	exit 1
fi

cd .. || exit 1
mv tmp/*AppImage* ./
